// can_id_map.h
#ifndef CAN_ID_MAP_H
#define CAN_ID_MAP_H

typedef enum {
	// CAN messages from INST
	CAN_ID_INST_HANDSHAKE_OK = 0x00,
	CAN_ID_INST_SEND_CONFIG_FILE_START,  // bandera de inicio de envío de datos. Cantidad en bytes, entero 2 bytes
    CAN_ID_INST_SEND_CONFIG_FILE_BYTE,   // paquete con 8 bytes. El último paquete es el módulo del tamaño total. 
    CAN_ID_INST_SEND_CONFIG_FILE_END,    // bandera de fin de envio. Se envia el checksum. Entero 2 bytes

	CAN_ID_INST_START_MEASURES = 0x100,
	CAN_ID_INST_CURRENT_PRIMARY,
	CAN_ID_INST_CURRENT_SECUNDARY,
	CAN_ID_INST_VOLTAGE_PRIMARY,
	CAN_ID_INST_VOLTAGE_SECONDARY,

	CAN_ID_INST_TEMP_TX_PRIMARY,
	CAN_ID_INST_TEMP_TX_SECONDARY,
	CAN_ID_INST_TEMP_CABLE_A,
	CAN_ID_INST_TEMP_CABLE_B,
	CAN_ID_INST_TEMP_PROBE_MAIN,
	CAN_ID_INST_TEMP_PROBE_SECONDARY,
	CAN_ID_INST_TEMP_CJC,
	CAN_ID_INST_END_MEASURES,
	CAN_ID_INST_STATUS,

	// DEBUG
	CAN_ID_INST_DIN_CHANGED,
	CAN_ID_INST_DOUT_CHANGED,
	CAN_ID_INST_VARIAC_VOLTAGE,

	CAN_ID_INST_ERROR_CFGFILE_SIZE = 0x200,
	CAN_ID_INST_ERROR_CFGFILE_CHKSUM,
	CAN_ID_INST_ERROR_CFGFILE_SEND_TIMEOUT,

	CAN_ID_INST_INFO_DOWN_CFG_FILE_OK = 0x280,

	// TEST data
	CAN_ID_INST_TEST_START_OK = 0x300,
	CAN_ID_INST_TEST_START_FAIL,
	CAN_ID_INST_TEST_FINISHED,
	CAN_ID_INST_TEST_PROFILE_SETPOINT,

	// CFG data
	// Payload sugerido: 1 byte (0x01 = Exito, 0x00 = Error)
	CAN_ID_ACK_SAVE_EEPROM, // Respuesta del command SAVE EEPROM
	CAN_ID_ACK_FACTORY_RESET, // Respuesta del comando FACTORY RESET

	// Temperature controller PID responses. Float payloads use IEEE-754,
	// little-endian byte order. ACK payload: data[0] = 1 on success.
	CAN_ID_INST_TEMP_PID_KP = 0x310,
	CAN_ID_INST_TEMP_PID_KI,
	CAN_ID_INST_TEMP_PID_KD,
	CAN_ID_INST_TEMP_PID_APPLY_ACK,
	CAN_ID_INST_TEMP_PID_DEFAULTS_ACK,

	// CAN messages to INSTRUMENTATION
	CAN_ID_ASK_HANDSHAKE = 0x400,
	CAN_ID_VOLTAGE_TX_PRIMARY_ADJ_LOW,
	CAN_ID_VOLTAGE_TX_PRIMARY_ADJ_HIGH,
	CAN_ID_VOLTAGE_TX_SECONDARY_ADJ_LOW,
	CAN_ID_VOLTAGE_TX_SECONDARY_ADJ_HIGH,
	CAN_ID_CURRENT_TX_PRIMARY_ADJ_LOW,
	CAN_ID_CURRENT_TX_PRIMARY_ADJ_HIGH,
	CAN_ID_CURRENT_TX_SECONDARY_ADJ_LOW,
	CAN_ID_CURRENT_TX_SECONDARY_ADJ_HIGH,
	CAN_ID_TEMP_PROBE_MAIN_ADJ_HIGH,
	CAN_ID_TEMP_PROBE_MAIN_ADJ_LOW,
	CAN_ID_TEMP_PROBE_SECONDARY_ADJ_HIGH,
	CAN_ID_TEMP_PROBE_SECONDARY_ADJ_LOW,
	CAN_ID_TEMP_TX_PRIMARY_ADJ_HIGH,
	CAN_ID_TEMP_TX_PRIMARY_ADJ_LOW,
	CAN_ID_TEMP_TX_SECONDARY_ADJ_HIGH,
	CAN_ID_TEMP_TX_SECONDARY_ADJ_LOW,
	CAN_ID_TEMP_CABLE_A_ADJ_HIGH,
	CAN_ID_TEMP_CABLE_A_ADJ_LOW,
    CAN_ID_TEMP_CABLE_B_ADJ_HIGH,
	CAN_ID_TEMP_CABLE_B_ADJ_LOW,
	CAN_ID_TEMP_CJC_ADJ_HIGH,
	CAN_ID_TEMP_CJC_ADJ_LOW,
	CAN_ID_HMI_ASK_EXPORT_CFG,
	CAN_ID_START_CFG_DATA,
    CAN_ID_CFG_DATA_FRAME,
    CAN_ID_CFG_DATA_END,
	CAN_ID_REQ_DOUT_TOGGLE,
	CAN_ID_REQ_VARIAC_SET_VOLTAGE,
	CAN_ID_REQ_START_TEST = 0x450,
	CAN_ID_REQ_STOP_TEST,
	CAN_ID_REQ_EMERGENCY_STOP,
	CAN_ID_REQ_SAVE_EEPROM = 0x460,
	CAN_ID_REQ_FACTORY_RESET,

	// Temperature controller PID commands. SET messages stage one float value;
	// APPLY commits all staged values. GET and RESTORE have empty payloads.
	CAN_ID_REQ_TEMP_PID_VALUES = 0x470,
	CAN_ID_REQ_TEMP_PID_SET_KP,
	CAN_ID_REQ_TEMP_PID_SET_KI,
	CAN_ID_REQ_TEMP_PID_SET_KD,
	CAN_ID_REQ_TEMP_PID_APPLY,
	CAN_ID_REQ_TEMP_PID_RESTORE_DEFAULTS,

	
	CAN_ID_LENGTH,
} can_id_map_e;

#endif // CAN_ID_MAP_H


