#ifndef EVENT_ENGINE_H
#define EVENT_ENGINE_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
	EVT_SYS_NULL = 0,	// Empty event
	// Commands from GUI -> System
	EVT_CMD_CHANGE_THEME,
	EVT_CMD_FULL_REPAINT,
	EVT_CMD_START_BOOT_SEQ,
	// Updates from System -> GUI
	EVT_SYS_NEW_GRAPH_VALUE,
	EVT_SYS_NEW_SAWTOOTH_VALUE,
	EVT_SYS_BOOT_CHECK_START,
	EVT_SYS_BOOT_EEPROM_STATE,
	EVT_SYS_BOOT_TOUCH_STATE,
	EVT_SYS_BOOT_BATT_STATE,
	EVT_SYS_BOOT_INST_STATE,
	EVT_SYS_BOOT_TIMES_COUNT,
	EVT_SYS_BOOT_RTC_DATE,
	EVT_SYS_BOOT_RTC_TIME,
	EVT_SYS_BOOT_PROGRESS_VALUE_CHANGE,
	EVT_SYS_BOOT_FINISHED,
	EVT_SYS_BOOT_EEPROM_TIMESTAMP,
	EVT_SYS_BOOT_BATTERY_TIMESTAMP,
	EVT_SYS_BOOT_INST_TIMESTAMP,
	EVT_SYS_BOOT_TOUCH_TIMESTAMP,
	EVT_SYS_BOOT_DATE_TIMESTAMP,
	EVT_SYS_BOOT_TIME_TIMESTAMP,
	EVT_SYS_BOOT_COUNTDOWN,
	EVT_SYS_BOOT_STOP_AUTO_SEQ,
	EVT_SYS_BOOT_CONTINUE_TO_DASHBOARD,
	EVT_SYS_BOOT_HANDSHAKE_OK,
	EVT_SYS_TIME_CHANGED,
	EVT_SYS_DATE_CHANGED,

	// Form selection
	EVT_SYS_SHOW_HOME_FORM,
	EVT_SYS_SHOW_CONFIG_FORM,
	EVT_SYS_SHOW_OPTIONS_FORM,
	EVT_SYS_SHOW_TEST_SELECTION_FORM,
	EVT_SYS_SHOW_FAULT_CONFIG_FORM,
	EVT_SYS_SHOW_NUMPAD_VAL_MODIFY,
	EVT_SYS_SHOW_TEST_CONFIRMATION,
	EVT_SYS_SHOW_TEST_RUNNING,
	EVT_SYS_SHOW_FINISHED_TEST,
	EVT_SYS_SHOW_CRUSH_CONFIG_FORM,
	EVT_SYS_SHOW_FILE_BROWSER,
	EVT_SYS_SHOW_SEQUENCE_PREVIEW_FORM,
	EVT_SYS_SHOW_SEQUENCE_CONFIG_FORM,
	EVT_SYS_SHOW_SEQUENCE_TEST_RUNNING,
	EVT_SYS_SHOW_ADJ_SELECT_VOLTAGE,
	EVT_SYS_SHOW_ADJ_SELECT_CURRENT,
	EVT_SYS_SHOW_ADJ_SELECT_TEMP,
	EVT_SYS_SHOW_ADJ_NUMPAD_FORM,
	EVT_SYS_SHOW_ADJ_CFG_SELECT_FORM,
	EVT_SYS_SHOW_ADJ_EXPORT_CFG,
	EVT_SYS_SHOW_ADJ_CFG_BROWSER,
	EVT_SYS_SHOW_ADJ_CFG_IMPORT_RESULT,
	EVT_SYS_SHOW_ADJ_RTC_FORM,
	EVT_SYS_SAVE_EEPROM, 
	EVT_SYS_FACTORY_RESET,
	EVT_SYS_SHOW_DEBUG_MENU,
	EVT_SYS_SHOW_DEBUG_IO_FORM,
	EVT_SYS_SHOW_VARIAC_DEBUG_FORM,
	EVT_SYS_SHOW_READINGS_DASHBOARD_FORM,
	EVT_SYS_SHOW_EEPROM_SYNC_RESULT_FORM,
	EVT_SYS_SHOW_VOLTAGE_PRESET_FORM,
	
	// Instrumentation events
	// CAN EVENTS
	EVT_CAN_INST_HANDSHAKE_OK,

	EVT_CAN_INST_CURRENT_PRIMARY,
	EVT_CAN_INST_CURRENT_SECUNDARY,
	EVT_CAN_INST_VOLTAGE_PRIMARY,
	EVT_CAN_INST_VOLTAGE_SECONDARY,

	EVT_CAN_INST_TEMP_TX_PRIMARY,
	EVT_CAN_INST_TEMP_TX_SECONDARY,
	EVT_CAN_INST_TEMP_PROBE_MAIN,
	EVT_CAN_INST_TEMP_PROBE_SECONDARY,
	EVT_CAN_INST_TEMP_CABLE_A,
	EVT_CAN_INST_TEMP_CABLE_B,
	EVT_CAN_INST_TEMP_CJC,

	EVT_CAN_INST_TC_TX_PRIMARY,
	EVT_CAN_INST_TC_TX_SECONDARY,
	EVT_CAN_INST_TC_PROBE_MAIN,
	EVT_CAN_INST_TC_PROBE_SECONDARY,
	EVT_CAN_INST_TC_CABLE_A,
	EVT_CAN_INST_TC_CABLE_B,
	EVT_CAN_INST_TC_CJC,
	EVT_CAN_INST_STATE,

	EVT_CAN_INST_CFG_LOAD_ERROR,
	EVT_CAN_INST_CFG_LOAD_OK,
	EVT_CAN_INST_TEST_START_OK,
	EVT_CAN_INST_TEST_START_FAIL,
	EVT_CAN_INST_TEST_FINISHED,
	
	// General events
	EVT_SYS_INST_SYNC_RESTORED,
	EVT_SYS_INST_UNSYNC,

	// USB Events
	EVT_SYS_USB_CONNECTED,
	EVT_SYS_USB_DISCONNECTED,
	EVT_SYS_USB_UNKNOWN_DEVICE,
	EVT_SYS_USB_POWER_FAULT,
	EVT_SYS_USB_START_LOG,
	EVT_SYS_USB_STOP_LOG,
	EVT_SYS_USB_LOG_ADDED,

	// Experiments cfg values
	EVT_SYS_FAULT_CFG_DURATION,	// Actual value saved in the cfg
	EVT_SYS_FAULT_CFG_CURRENT,
	EVT_SYS_FAULT_CFG_PRESET_VOLTAGE,
	EVT_SYS_FAULT_CFG_CALIBER,
	EVT_SYS_FAULT_CFG_IS_HIGH_RESISTENCE,
	EVT_SYS_CRUSH_CFG_TEMP,
	EVT_SYS_CRUSH_CFG_DURATION,
	EVT_SYS_CRUSH_CFG_CALIBER,
	EVT_SYS_CRUSH_CFG_IS_HIGH_RESISTENCE,
	EVT_SYS_PROFILE_CFG_CALIBER,


	EVT_SYS_NUMPAD_MOD_FAULT_CFG_CURRENT, // Value passed to the numpad
	EVT_SYS_NUMPAD_MOD_FAULT_CFG_DURATION,
	EVT_SYS_NUMPAD_MOD_FAULT_CFG_PRESET_VOLTAGE,
	EVT_SYS_NUMPAD_MOD_FAULT_CFG_CALIBER,	
	EVT_SYS_NUMPAD_MOD_FAULT_CFG_IS_HIGH_RESISTENCE,	
	EVT_SYS_NUMPAD_MOD_CRUSH_CFG_TEMP, // Value passed to the numpad
	EVT_SYS_NUMPAD_MOD_CRUSH_CFG_DURATION,
	EVT_SYS_NUMPAD_MOD_CRUSH_CFG_CALIBER,	
	EVT_SYS_NUMPAD_MOD_CRUSH_CFG_IS_HIGH_RESISTENCE,	

	EVT_SYS_NUMPAD_MOD_PROFILE_CFG_CALIBER,

	EVT_SYS_FAULT_CFG_SUBMIT_DURATION,	// Value passed to the instrumentation
	EVT_SYS_FAULT_CFG_SUBMIT_CURRENT,
	EVT_SYS_FAULT_CFG_SUBMIT_PRESET_VOLTAGE,
	EVT_SYS_FAULT_CFG_SUBMIT_CALIBER,
	EVT_SYS_FAULT_CFG_SUBMIT_IS_HIGH_RESISTENCE,

	EVT_SYS_CRUSH_CFG_SUBMIT_DURATION,	// Value passed to the instrumentation
	EVT_SYS_CRUSH_CFG_SUBMIT_TEMP,
	EVT_SYS_CRUSH_CFG_SUBMIT_CALIBER,
	EVT_SYS_CRUSH_CFG_SUBMIT_IS_HIGH_RESISTENCE,

	EVT_SYS_PROFILE_CFG_SUBMIT_CALIBER,
	
	EVT_UI_BOOT_TOGGLE_CONTINUE_LABEL,
	
	// Test related events
	EVT_SYS_START_TEST,
	EVT_SYS_TEST_START_ERROR_FLAG,
	EVT_SYS_TEST_FINISHED_OK,
	EVT_SYS_TEST_FINISHED_FAIL,

	EVT_UI_TEST_UPDATE_TIME,
	EVT_UI_TEST_UPDATE_PROGRESS,
	EVT_UI_TEST_UPDATE_STABILITY_TIME,
	EVT_SYS_TEST_SAVED_LOG_NAME,

	EVT_UI_GRAPH_CURRENT_VALUE,
	EVT_UI_GRAPH_TEMP_VALUE,
	EVT_SYS_TEST_EMERGENCY_STOPPED,
	
	// Cfg events
    EVT_SYS_CFG_IMPORT_SUCCESS,
    EVT_SYS_CFG_IMPORT_ERROR, 
	EVT_SYS_CFG_IMPORT_TIMEOUT,

    EVT_SYS_CFG_EXPORT_SUCCESS,
    EVT_SYS_CFG_EXPORT_ERROR, 
	EVT_SYS_CFG_EXPORT_TIMEOUT,

	EVT_CAN_INST_ACK_FACTORY_RESET,
	EVT_CAN_INST_ACK_SAVE_EEPROM, 
	// Debug events
	EVT_CAN_INST_DIN_CHANGED,
	EVT_SYS_REQ_DOUT_TOGGLE,
	EVT_CAN_INST_DOUT_CHANGED,
	EVT_CAN_INST_VARIAC_VOLTAGE,
	EVT_CAN_INST_VARIAC_STATUS,

	NUM_EVENTS,
} EventID_e;

typedef union {
	uint32_t ui32;
	int32_t i32;
	float f32;
	void *ptr;
	const char *str;
	bool bool_;
} EventParam_t;

typedef struct {
	EventID_e id;
	EventParam_t arg;
} SystemEvent_t;

typedef void (*EventHandler_fn)(EventParam_t arg);

bool Event_Post(EventID_e id, EventParam_t arg);

bool Event_Receive(SystemEvent_t *pEvent);

bool Event_Subscribe(EventID_e id, EventHandler_fn handler);

bool Event_Dispatch(void);
bool Event_Init(void);

#endif	//EVENT_ENGINE_H



