#ifndef SYS_MANAGER_H
#define SYS_MANAGER_H

typedef enum {
	SYS_BOOT_INIT_START = 0,
	SYS_BOOT_CHECK_EEPROM,
	SYS_BOOT_TOUCH_CALIB,
	SYS_BOOT_BATT_STATE,
	SYS_BOOT_CHECK_INST,
	SYS_BOOT_STARTUP_TIMES,
	SYS_BOOT_RTC_DATE,
	SYS_BOOT_RTC_TIME,	
	SYS_BOOT_WAIT_5_SECONDS,
	SYS_SHOW_DASHBOARD_FORM,
	SYS_CFG_IMPORT_START_TIMEOUT,
	SYS_CFG_IMPORT_TIMEOUT,
	SYS_CFG_EXPORT_START_TIMEOUT,
	SYS_CFG_EXPORT_TIMEOUT,
	SYS_TEST_INIT,
	SYS_TEST_RUNNING,
	SYS_TEST_STOP,
	SYS_TEST_START_FAIL,
	SYS_TEST_WAIT_CONFIRM,
	SYS_EMERGENCY_STOP,
	SYS_IDLE,
} SysState_e;

void SysManager_Init(void);

void SysManager_Task(void);


#endif // SYS_MANAGER_H 